version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: 