version: '3.8'
services:
  dbthinh:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1444:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    networks:
      - thinh-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    container_name: thinh-itc-backend
    image: thinh584/itc_backend:latest
    restart: always
    build:
      dockerfile: ITC.API/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - dbthinh
    networks:
      - thinh-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=dbthinh;Database=InterTransConnectDB;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=true;TrustServerCertificate=true;
      

volumes:
  sqlserver_data:

networks:
  thinh-network:
    name: thinh-network
    external: true







